"""add users and per-user scoping

Revision ID: 08c46d12eb5b
Revises: 6c4ca866a562
Create Date: 2026-06-10 15:15:35.162398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c46d12eb5b'
down_revision: Union[str, Sequence[str], None] = '6c4ca866a562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # Rows created before auth existed belong to no user and cannot satisfy
    # the NOT NULL user_id below; remove them (children first for FKs).
    op.execute('DELETE FROM budget_entries')
    op.execute('DELETE FROM expenses')
    op.execute('DELETE FROM categories')

    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_budget_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_budget_entries_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_category_name_group'), type_='unique')
        batch_op.create_unique_constraint('uq_category_name_group', ['user_id', 'name', 'group'])
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_categories_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_expenses_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_expenses_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_constraint('uq_category_name_group', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_category_name_group'), ['name', 'group'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_budget_entries_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_budget_entries_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
