"""create categories, budget_entries, expenses

Revision ID: 6c4ca866a562
Revises: 
Create Date: 2026-06-10 14:36:52.685153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4ca866a562'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group', sa.Enum('income', 'bills', 'spending', 'holiday', 'debt', name='categorygroup'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group', name='uq_category_name_group')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spend_date', sa.Date(), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_spend_date'), ['spend_date'], unique=False)

    op.create_table('budget_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'year', 'month', name='uq_budget_cell')
    )
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_entries_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_entries_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_entries_year'))
        batch_op.drop_index(batch_op.f('ix_budget_entries_category_id'))

    op.drop_table('budget_entries')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_spend_date'))

    op.drop_table('expenses')
    op.drop_table('categories')
    # ### end Alembic commands ###
